//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.20 at 03:43:19 PM IST 
//


package com.hexaware.workquikr.console.util.adapter.jaxb.ws;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.hexaware.workquikr.console.util.adapter.jaxb.ws.Adapter.Operations.Operation;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="operations" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="operation" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="inputClass" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="wsdlURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="serviceName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="portName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="jaxbPackageName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="targetNamespace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="return-datatype" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "type",
    "operations"
})
@XmlRootElement(name = "adapter")
public class Adapter {

    protected String name;
    protected String type;
    protected Adapter.Operations operations;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the operations property.
     * 
     * @return
     *     possible object is
     *     {@link Adapter.Operations }
     *     
     */
    public Adapter.Operations getOperations() {
        return operations;
    }

    /**
     * Sets the value of the operations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Adapter.Operations }
     *     
     */
    public void setOperations(Adapter.Operations value) {
        this.operations = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="operation" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="inputClass" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="wsdlURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="serviceName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="portName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="jaxbPackageName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="targetNamespace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="return-datatype" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "operation"
    })
    public static class Operations {

        protected List<Adapter.Operations.Operation> operation;

        /**
         * Gets the value of the operation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the operation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOperation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Adapter.Operations.Operation }
         * 
         * 
         */
        public List<Adapter.Operations.Operation> getOperation() {
            if (operation == null) {
                operation = new ArrayList<Adapter.Operations.Operation>();
            }
            return this.operation;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="inputClass" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="wsdlURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="serviceName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="portName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="jaxbPackageName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="targetNamespace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="return-type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="return-datatype" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "inputClass",
            "wsdlURL",
            "serviceName",
            "portName",
            "jaxbPackageName",
            "targetNamespace",
            "returnType",
            "returnDatatype"
        })
        public static class Operation {

            protected String name;
            protected String inputClass;
            protected String wsdlURL;
            protected String serviceName;
            protected String portName;
            protected String jaxbPackageName;
            protected String targetNamespace;
            @XmlElement(name = "return-type")
            protected String returnType;
            @XmlElement(name = "return-datatype")
            protected String returnDatatype;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the inputClass property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInputClass() {
                return inputClass;
            }

            /**
             * Sets the value of the inputClass property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInputClass(String value) {
                this.inputClass = value;
            }

            /**
             * Gets the value of the wsdlURL property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getWsdlURL() {
                return wsdlURL;
            }

            /**
             * Sets the value of the wsdlURL property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWsdlURL(String value) {
                this.wsdlURL = value;
            }

            /**
             * Gets the value of the serviceName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getServiceName() {
                return serviceName;
            }

            /**
             * Sets the value of the serviceName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setServiceName(String value) {
                this.serviceName = value;
            }

            /**
             * Gets the value of the portName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPortName() {
                return portName;
            }

            /**
             * Sets the value of the portName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPortName(String value) {
                this.portName = value;
            }

            /**
             * Gets the value of the jaxbPackageName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getJaxbPackageName() {
                return jaxbPackageName;
            }

            /**
             * Sets the value of the jaxbPackageName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setJaxbPackageName(String value) {
                this.jaxbPackageName = value;
            }

            /**
             * Gets the value of the targetNamespace property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTargetNamespace() {
                return targetNamespace;
            }

            /**
             * Sets the value of the targetNamespace property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTargetNamespace(String value) {
                this.targetNamespace = value;
            }

            /**
             * Gets the value of the returnType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReturnType() {
                return returnType;
            }

            /**
             * Sets the value of the returnType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReturnType(String value) {
                this.returnType = value;
            }

            /**
             * Gets the value of the returnDatatype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getReturnDatatype() {
                return returnDatatype;
            }

            /**
             * Sets the value of the returnDatatype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setReturnDatatype(String value) {
                this.returnDatatype = value;
            }

        }

    }
    public Map<String, Adapter.Operations.Operation> getProcedureAsMap() {
  		Map<String, Adapter.Operations.Operation> map=new HashMap<String, Adapter.Operations.Operation>();
  		Operations list= getOperations();
  		List<Adapter.Operations.Operation> lis=list.getOperation();
  		for (Operation procedure : lis) {
  			map.put(procedure.getName(), procedure);
  		}
  		return map;
  	}

}
